AWSTemplateFormatVersion: 2010-09-09
Description: This template creates a S3 bucket with SSE-S3 encryption enabled and
  a S3 bucket policy that allows only secure transport.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  BucketNameSuffix:
    ConstraintDescription: Bucket name suffix (e.g., global unique id); bucket name is ${Environment}-${BucketNameSuffix}
    Description: Bucket name suffix (e.g., global unique id); bucket name is ${Environment}-${BucketNameSuffix}
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub ${EnvironmentName}-${BucketNameSuffix}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      VersioningConfiguration:
        Status: Suspended

  S3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Id: S3BucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: AllowOnlySecureTransport
            Action:
              - s3:*
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
            Effect: Deny
            Principal: '*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}'
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
          - Sid: DenyIncorrectEncryptionHeader
            Action:
              - s3:PutObject
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'AES256'
            Effect: Deny
            Principal: '*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'
          - Sid: DenyUnencryptedObjectUploads
            Action:
              - s3:PutObject
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': 'true'
            Effect: Deny
            Principal: '*'
            Resource:
              - !Sub 'arn:aws:s3:::${S3Bucket}/*'

Outputs:
  S3BucketName:
    Description: S3 Bucket Name
    Value: !Ref S3Bucket
